apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: staging
spec:
  type: LoadBalancer
  selector:
    app: laravel
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: staging
spec:
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: aly666/laravel:0.0.6-stag
          env:
            - name: LARAVEL_DB_HOST
              value: mysql-service-laravel.staging.svc.cluster.local
            - name: LARAVEL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-pass-lr
                  key: MYSQL_ROOT_PASSWORD
            - name: LARAVEL_DB_USER
              value: root
            - name: LARAVEL_DB_NAME
              value: laravel
          ports:
          - containerPort: 80
            name: laravel
          volumeMounts:
            - name: laravel-data
              mountPath: /var/www
      volumes:
        - name: laravel-data
          persistentVolumeClaim:
            claimName: wp-pv-claim

