apiVersion: v1
kind: Service
metadata:
  name: landing-page
  namespace: production
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: landing-page
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      imagePullSecrets:
        - name: dockerhub-private
      containers:
      - name: landing-page
        image: aly666/landing-page:1.0.0-prod
        ports:
        - containerPort: 80

