apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: production
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:5.8.3-php7.4-apache
          env:
            - name: WORDPRESS_DB_HOST
              value: database-1.ctfbz2p2huco.ap-southeast-1.rds.amazonaws.com
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-pass-wp
                  key: DB_USER
            - name: WORDPRESS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: my-pass-wp
                  key: DB_PASS      
            - name: WORDPRESS_DB_USERNAME
              value: admin
            - name: WORDPRESS_DB_PASSWORD
              value: password
            - name: WORDPRESS_DB_NAME
              value: wordpress
          ports:
          - containerPort: 80
            name: wordpress
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wp-pv-claim