apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-landing
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: landing.pastikerja.xyz
    http:
      paths:
        - path:
          backend:
            serviceName: landing-page
            servicePort: 80
