apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fb        
  namespace : production
spec:
  scaleTargetRef:
    apiVersion: apps/v1     
    kind: Deployment
    name: fb        
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20


