apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-fb
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: fb.pastikerja.xyz
    http:
      paths:
        - path:
          backend:
            serviceName: fb
            servicePort: 80
