apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb
  namespace: production
  labels:
    app: fb
    name : fb
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/approvals: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fb
  template:
    metadata:
      labels:
        app: fb
    spec:
      imagePullSecrets:
        - name: dockerhub-private
      containers:
      - name: fb
        image: aly666/fb-prod:1.0.2
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: database-1.ctfbz2p2huco.ap-southeast-1.rds.amazonaws.com
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: fb
  namespace: production
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: fb

