apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: laravel
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lv-pv-claim
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: production
spec:
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: aly666/laravel:0.0.1-prod
          env:
            - name: LARAVEL_DB_HOST
              value: mysql.production.svc.cluster.local
            - name: LARAVEL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-pass-lr
                  key: DB_USER
            - name: LARAVEL_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: my-pass-lr
                  key: DB_PASS      
            - name: LARAVEL_DB_USERNAME
              value: root
            - name: LARAVEL_DB_NAME
              value: laravel
          ports:
          - containerPort: 80
            name: laravel
          volumeMounts:
            - name: laravel-data
              mountPath: /var/www
      volumes:
        - name: laravel-data
          persistentVolumeClaim:
            claimName: lv-pv-claim
